name: Christin Kardos
favicon: null
layout_spectrum: 0.50044
typography_spectrum: 0.09713
title: 'Christin Kardos: Digital Cheerleader'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#120026'
    - '#f8f4c4'
    - '#9e6153'
    - '#78323d'
    - '#63dcc3'
  brandStrength: 1
  lightness: 0.4375
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
