name: Christin Kardos
favicon: null
layout_spectrum: 0.50044
typography_spectrum: 0.09713
title: 'Christin Kardos: Digital Cheerleader'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ece5dd'
    - '#4cac87'
    - '#110907'
    - '#2a6d4e'
    - '#996b5c'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
