name: Christin Kardos
favicon: null
layout_spectrum: 0.42529
typography_spectrum: 0.49347
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4efe9'
    - '#050100'
    - '#34b686'
    - '#e3b198'
    - '#50352e'
  brandStrength: 0.375
  lightness: 0.7729063401930034
  saturation: 0.5
  rhythmicContrast: 0.18888669670559466
purpose: []
