name: Christin Kardos
favicon: null
layout_spectrum: 0.91174
typography_spectrum: 0.11058
title: 'Christin Kardos: Digital Cheerleader'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bec7d0'
    - '#000000'
    - '#8d9444'
    - '#fffffd'
    - '#880006'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
